find_test_cases_task:
  description: >
    Carefully analyze the simplified HTML of the webpage, list of active elements and write the list of testcases that 
    need to be checked. Fill the following fields of testcase object: title, description and expected_result. Don't 
    fill the steps and priority fields - they will be filled as a separate task. At this stage you should be attentive
    to find as many testcases as possible. Testcases should not be complex. Don't combine different testcases (like 
    good and bad values in inputs, allowed and disallowed file types or size) into one. Check the allowed and disallowed
    values in inputs in separate tasks.
    
    [page_description]
    {page_description}
    [/page_description]
    
    [simplified_html]
    {simplified_html}
    [/simplified_html]
    
    [active_elements]
    {active_elements}
    [/active_elements]

  expected_output: >
    A list of testcases that need to be implemented. Don't fill the steps and priority fields - they will be filled
    as a separate task. If you can separate expected_results into several simple clauses, do it.
  agent: senior_qa

fill_test_case_task:
  description: >
    Carefully analyze the simplified HTML of the webpage, list of active elements and fill the fields "steps" and 
    "priority" of the testcase object.
    
    Priority Levels:
    * Low Priority ("low"): Test cases that focus on non-critical aspects of a web page. These include aesthetic 
      elements, such as the correct alignment of buttons, spelling errors in non-critical areas, or missing tooltips. 
      Issues detected by these tests do not affect core functionality and user operations, but fixing them improves the 
      user experience.
    * Medium Priority ("medium"): Test cases that address functional elements of a web page that are important but not 
      crucial to the main workflow. These might involve verifying the validation of optional fields in a form, ensuring 
      that certain non-core features work as intended, or checking usability elements that improve interaction but don’t 
      block key functionalities. Problems here might inconvenience users but do not prevent them from achieving primary 
      goals.
    * High Priority ("high"): Test cases that focus on critical functions of a web page. This includes verifying the 
      functionality of core features like the submission of forms, the ability to log in, key interactions with buttons 
      that impact data flow, or security features such as input validation for sensitive fields. Failures here could 
      prevent the web page from achieving its main purpose or expose critical vulnerabilities.
    
    [page_description]
    {page_description}
    [/page_description]

    [simplified_html]
    {simplified_html}
    [/simplified_html]

    [active_elements]
    {active_elements}
    [/active_elements]

    Testcase:    
    {testcase_object}
  expected_output: >
    Fill the fields "steps" and "priority" of the testcase object.

  agent: senior_qa
