find_test_cases_task:
  description: >
    Carefully analyze the simplified HTML of the webpage, list of active elements and write the list of testcases that 
    need to be checked. Fill the following fields of testcase object: title, description and expected_result. Don't 
    fill the steps and priority fields - they will be filled as a separate task. At this stage you should be attentive
    to find as many testcases as possible.
    
    [page_description]
    {page_description}
    [/page_description]
    
    [simplified_html]
    {simplified_html}
    [/simplified_html]
    
    [active_elements]
    {active_elements}
    [/active_elements]

  expected_output: >
    A list of testcases that need to be implemented. Don't fill the steps and priority fields - they will be filled
    as a separate task.
  agent: senior_qa

fill_test_case_task:
  description: >
    Carefully analyze the simplified HTML of the webpage, list of active elements and fill the fields "steps" and 
    "priority" of the testcase object.
    
    [page_description]
    {page_description}
    [/page_description]

    [simplified_html]
    {simplified_html}
    [/simplified_html]

    [active_elements]
    {active_elements}
    [/active_elements]

    Testcase:    
    {testcase_object}
  expected_output: >
    Fill the fields "steps" and "priority" of the testcase object.

  agent: senior_qa
