find_test_cases_task:
  description: >
    Carefully analyze the simplified HTML of the webpage, list of active elements and write the list of testcases that 
    need to be checked. 
    
    [page_description]
    {page_description}
    [/page_description]
    
    [simplified_html]
    {simplified_html}
    [/simplified_html]
    
    [active_elements]
    {active_elements}
    [/active_elements]

  expected_output: >
    A list of test cases that need to be implemented.
  agent: senior_qa

fill_test_case_task:
  description: >
    Carefully analyze the simplified HTML of the webpage, list of active elements and write the steps to implement the 
    testcase with the expected result(s).
    
    [page_description]
    {page_description}
    [/page_description]

    [simplified_html]
    {simplified_html}
    [/simplified_html]

    [active_elements]
    {active_elements}
    [/active_elements]

    Testcase:    
    [title]
    {testcase_title}
    [/title]
  expected_output: >
    Fill the test case object which has the following structure:

        {
            "title": "Testcase title",
            "steps": [
                "Step 1",
                "Step 2",
                ...
                "Step N"
            ]
            "result": [
                "Expected result 1 (like Button "Click" should be enabled, or field should be highlighted in red)",
            ] 
        }
  agent: senior_qa
